# -*- coding: utf-8 -*-
from models.squeezenet import *
from models.vgg import *
#from dpn import *
#from lenet import *
#from senet import *
#from pnasnet import *
from models.densenet import *
#from googlenet import *
#from models.shufflenet import *
from models.resnet import *
from models.resnext import *
#from preact_resnet import *
#from mobilenet import *
from models.mobilenetv2 import *
from models.my_resnetV2 import *
from models.my_resnetV3 import *
from models.ShuffleNetV2 import *
from models.other_shufflenetv2 import *
